name: drupalcampnyc
recipe: drupal8
config:
  php: 7.1
  via: nginx
  webroot: web
  database: mariadb
  xdebug: false
services:
  appserver:
    overrides:
      environment:
        DRUSH_OPTIONS_URI: https://drupalcampnyc.lndo.site
    run:
      - cp -n setup/lando-basic/settings.local.php web/sites/default/settings.local.php
      - composer install
