ahoyapi: v2
commands:
  robo:
    usage: Call our robo commands [Advanced users only]
    cmd: vendor/bin/robo --load-from ./scripts/robo "$@"
    hide: true
  bash:
    usage: Open an interactive bash shell in a container [Advanced users only]
    cmd: ahoy robo bash "$@"
    hide: true
  shell:
    usage: Open an interactive bourne shell in a container [Advanced users only]
    cmd: ahoy robo shell "$@"
    hide: true
  docker:
    usage: Interact with the docker daemon.  (Linux users have direct access). [Advanced users only]
    cmd: ahoy robo docker "$@"
    hide: true
  key-prep:
    usage: Process private key to one-liner [Advanced users only]
    cmd: ahoy robo "key:prep" "$@"
    hide: true
  log:
    usage: Tail a service log. Specify one of [database, php, web, front-end, cli]
    cmd: ahoy robo log "$@"
  cast-off:
    usage: Launch the global tools needed for local development. Run this command once after you boot your computer.
    cmd: |
      ahoy robo boot && #make sure boot is successful
      ahoy robo "boot:dns"
  harbor:
    usage: Build the harbor for your docks.  Run this command once after the first time you `composer install` a dp-docker project.
    cmd: |
      ahoy robo "setup:docker" &&
      ahoy robo "setup:dns"
  launch:
    usage: Launch this project site.
    cmd: ahoy robo docker:compose
  dock:
    usage: Stops this project site and 'returns to port.'
    cmd: ahoy robo dock
  drush:
    usage: Run drush commands within the drupal site. Follow `ahoy drush` with the drush command to be run.
    cmd: ahoy robo drush "$@"
  drupal:
    usage: Run drupal console commands within the drupal site. Follow `ahoy drupal` with the drupal console command to be run.
    cmd:  ahoy robo drupal "$@"
  gulp:
    usage: Pass commands to gulp within the container. Follow `ahoy gulp` with the gulp command to be run.
    cmd: ahoy robo gulp "$@"
  npm:
    usage: Pass commands to npm within the container. Follow `ahoy npm` with the npm command to be run.
    cmd: ahoy robo npm "$@"
  npm-update:
    usage: Install node modules and recreate the shrinkwrap.
    cmd: ahoy robo "npm:update"
  compile:
    usage: Compile the site theme assets.
    cmd: ahoy robo gulp build
  rebuild:
    usage: Sync with a server database and compile front end. Pass an environment argument to use with drush alias [@shortname.env]
    cmd: ahoy robo rebuild "$@"
  sql:
    usage: Displays connection info for the database service.
    cmd: ahoy robo connect:sql
