sitegroup: example

deploy_tasks:
  development:
    before_deploy:
      - APP_ENV=test composer install --no-dev --optimize-autoloader
      - cd web/themes/drupaleurope && npm install
      - cd web/themes/drupaleurope && npm run build
    after_deploy:
      - cd web && drush -y sql-drop
      - cd web && drush -y sql-sync @master default
      - cd web && drush -y rsync @master:%files default:%files
      - cd web && drush -y updb --cache-clear=0
      - cd web && drush -y cim
      - cd web && drush -y entup
      - cd web && drush -y cr
  production:
    before_deploy:
      - APP_ENV=prod composer install --no-dev --optimize-autoloader
      - cd web/themes/drupaleurope && npm install
      - cd web/themes/drupaleurope && npm run build
    after_deploy:
      - cd web && drush -y updb --cache-clear=0
      - cd web && drush -y cim
      - cd web && drush -y entup
      - cd web && drush -y cr

shared:
  production:
    - src: files
      dst: web/sites/default/files
    - src: private-files
      dst: web/sites/default/private-files
