name: drupalcampnyc
recipe: pantheon
config:
  framework: drupal8
  site: drupalcampnyc
  id: 36d6210e-0ea0-4579-9a00-a8d3ef891b81
  xdebug: false
  index: false
  edge: true
  cache: true
services:
  node:
    type: node:10
    run:
      - cd /app/web/themes/drupalnyc && npm install
      - cd /app/web/themes/drupalnyc && npm run build
tooling:
  npm:
    service: node
    cmd: npm --prefix /app/web/themes/drupalnyc
  node:
    service: node
  pull:
    options:
      code:
        default: none
      database:
        default: test
      files:
        default: test
  push: disabled
excludes:
  - vendor
  - web/themes/drupaleurope/node_modules
  - web/themes/drupalnyc/node_modules
