module:
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  allowed_formats: 0
  auto_entitylabel: 0
  autocomplete_deluxe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  classy_paragraphs: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  config_ignore_readonly: 0
  config_readonly: 0
  config_split: 0
  content_moderation: 0
  contextual: 0
  csv_serialization: 0
  ctools: 0
  ctools_block: 0
  ctools_views: 0
  datalayer: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  de_core: 0
  de_core_actions: 0
  dropzonejs: 0
  dropzonejs_eb_widget: 0
  dynamic_page_cache: 0
  editor: 0
  empty_fields: 0
  entity: 0
  entity_browser: 0
  entity_browser_enhanced: 0
  entity_browser_entity_form: 0
  entity_reference_revisions: 0
  facebook_pixel: 0
  field: 0
  field_group: 0
  field_permissions: 0
  file: 0
  filter: 0
  flag: 0
  google_tag: 0
  help: 0
  history: 0
  honeypot: 0
  image: 0
  inline_entity_form: 0
  inline_form_errors: 0
  link: 0
  linkit: 0
  markup: 0
  maxlength: 0
  media: 0
  menu_block: 0
  menu_ui: 0
  message_banner: 0
  metatag: 0
  metatag_twitter_cards: 0
  metatag_views: 0
  node: 0
  nyc_core: 0
  options: 0
  override_node_options: 0
  pantheon_advanced_page_cache: 0
  paragraphs_type_permissions: 0
  path: 0
  path_alias: 0
  rdf: 0
  redirect: 0
  redirect_404: 0
  redis: 0
  responsive_image: 0
  rest: 0
  scheduler: 0
  serialization: 0
  sessionize_embed_block: 0
  shariff: 0
  simple_sitemap: 0
  smart_trim: 0
  social_media_links: 0
  svg_image: 0
  svg_image_responsive: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  user: 0
  viewsreference: 0
  webform: 0
  webform_image_select: 0
  webform_node: 0
  webform_scheduled_email: 0
  webform_submission_log: 0
  webform_templates: 0
  workflows: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  paragraphs: 11
  minimal: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  drupaleurope: 0
  adminimal_theme: 0
  drupalnyc: 0
profile: minimal
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
