definitions:
  contact__site_page:
    weight: -39
    menu_name: main
    parent: ''
    enabled: true
    expanded: true
  standard__front_page:
    weight: -50
    menu_name: main
    parent: ''
    expanded: false
    enabled: true
