cookie_lifetime: 100
domain: ''
domains_option: 1
domains_list: ''
eu_only: false
eu_only_js: false
exclude_paths: "/admin\r\n/admin/*\r\n/batch\r\n/node/add*\r\n/node/*/*\r\n/user/*/*\r\n/infoscreen/*\r\n/infoscreen/*/*"
exclude_admin_theme: false
langcode: en
popup_agreed:
  value: '<h2>Thank you for accepting cookies</h2><p>You can now hide this message or find out more about cookies.</p>'
  format: restricted_html
popup_agree_button_message: 'OK, It sounds fine'
popup_agreed_enabled: false
popup_bg_hex: ''
popup_clicking_confirmation: true
popup_scrolling_confirmation: false
popup_delay: 500
show_disagree_button: false
popup_disagree_button_message: 'Give me more info'
popup_enabled: true
popup_find_more_button_message: 'More info'
popup_height: null
popup_hide_agreed: false
popup_hide_button_message: Hide
popup_info:
  value: '<h2>We use cookies!</h2><p>A cookie is a small text file containing information that a website transfers to your computer’s hard disk for record-keeping purposes and allows us to analyse our site traffic patterns. It does not contain chocolate chips, you cannot eat it and there is no special hidden jar.</p>'
  format: restricted_html
mobile_popup_info:
  value: '<h2>We use cookies!</h2><p>It is not some chocolate chipped variant, but used to analyse traffic patterns on this website and identify potential technical or content problems.</p>'
  format: restricted_html
mobile_breakpoint: 768
popup_link: /privacy
popup_link_new_window: true
popup_position: false
fixed_top_position: true
popup_text_hex: ''
popup_width: ''
use_bare_css: true
disagree_do_not_show_popup: false
reload_page: false
cookie_name: hidden-cookie-jar
exclude_uid_1: false
better_support_for_screen_readers: false
use_mobile_message: true
_core:
  default_config_hash: OlBvbDcm2PUT2i28p3oNpuKaUKbbK4qjfrAyYxvd0B8
method: default
disagree_button_label: 'No, thanks'
disabled_javascripts: ''
whitelisted_cookies: ''
consent_storage_method: do_not_store
withdraw_message:
  value: '<h2>We use cookies on this site to enhance your user experience</h2><p>You have given your consent for us to set cookies.</p>'
  format: full_html
withdraw_action_button_label: 'Withdraw consent'
withdraw_tab_button_label: 'Privacy settings'
withdraw_enabled: false
popup_info_template: legacy
cookie_categories: ''
enable_save_preferences_button: true
save_preferences_button_label: 'Save preferences'
accept_all_categories_button_label: 'Accept all cookies'
fix_first_cookie_category: true
select_all_categories_by_default: false
withdraw_button_on_info_popup: false
domain_all_sites: false
uuid: 8bc7f55c-f8fc-4bc9-9a56-fd6befc4d1c5
