_core:
  default_config_hash: 9KCLeaYP64BuA6I0xq5nzO0OipvgEH-YtTIFrCaLkH0
shariff_services:
  twitter: twitter
  facebook: facebook
shariff_theme: colored
shariff_css: complete
shariff_orientation: horizontal
