shariff_css: complete
shariff_theme: colored
shariff_orientation: horizontal
shariff_services:
  twitter: twitter
  facebook: facebook
  googleplus: googleplus
_core:
  default_config_hash: 9KCLeaYP64BuA6I0xq5nzO0OipvgEH-YtTIFrCaLkH0
