name: drupalcampnyc
config:
  xdebug: false
services:
  appserver:
    overrides:
      environment:
        DRUSH_OPTIONS_URI: https://drupalcampnyc.lndo.site
    run:
      - cp -n setup/lando-pantheon/settings.local.php web/sites/default/settings.local.php
      - composer install
