definitions:
  contact__site_page:
    enabled: false
    menu_name: main
    parent: ''
    weight: -41
    expanded: true
  standard__front_page:
    weight: -50
    menu_name: main
    parent: ''
    expanded: false
    enabled: true
