definitions:
  contact__site_page:
    weight: -43
    menu_name: main
    parent: ''
    expanded: true
    enabled: true
  standard__front_page:
    weight: -50
    menu_name: main
    parent: ''
    expanded: false
    enabled: true
