definitions:
  contact__site_page:
    enabled: true
    weight: -45
    expanded: true
    menu_name: main
    parent: ''
  standard__front_page:
    weight: -50
    menu_name: main
    parent: ''
    expanded: false
    enabled: true
