---
site_shortname: dcnyc16
site_theme_name: dcnyc
site_theme_path: web/themes/custom/dcnyc
site_alias_name: drupalcampnyc
site_folder: default
site_proxy_origin_url: https://www.drupalcamp.nyc

jira_project_key:
